# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import smart_hospital_pb2 as smart__hospital__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in smart_hospital_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/smarthospital.DeviceService/ListDevices',
                request_serializer=smart__hospital__pb2.Empty.SerializeToString,
                response_deserializer=smart__hospital__pb2.DeviceList.FromString,
                _registered_method=True)


class DeviceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=smart__hospital__pb2.Empty.FromString,
                    response_serializer=smart__hospital__pb2.DeviceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smarthospital.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smarthospital.DeviceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.DeviceService/ListDevices',
            smart__hospital__pb2.Empty.SerializeToString,
            smart__hospital__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PatientMonitorServiceStub(object):
    """services for Monitor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/smarthospital.PatientMonitorService/GetState',
                request_serializer=smart__hospital__pb2.DeviceIdRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.PatientMonitorState.FromString,
                _registered_method=True)
        self.SetPower = channel.unary_unary(
                '/smarthospital.PatientMonitorService/SetPower',
                request_serializer=smart__hospital__pb2.SetMonitorPowerRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetAlarmEnabled = channel.unary_unary(
                '/smarthospital.PatientMonitorService/SetAlarmEnabled',
                request_serializer=smart__hospital__pb2.SetMonitorAlarmRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetThresholds = channel.unary_unary(
                '/smarthospital.PatientMonitorService/SetThresholds',
                request_serializer=smart__hospital__pb2.SetMonitorThresholdsRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)


class PatientMonitorServiceServicer(object):
    """services for Monitor
    """

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAlarmEnabled(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetThresholds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PatientMonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=smart__hospital__pb2.DeviceIdRequest.FromString,
                    response_serializer=smart__hospital__pb2.PatientMonitorState.SerializeToString,
            ),
            'SetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPower,
                    request_deserializer=smart__hospital__pb2.SetMonitorPowerRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetAlarmEnabled': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAlarmEnabled,
                    request_deserializer=smart__hospital__pb2.SetMonitorAlarmRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetThresholds': grpc.unary_unary_rpc_method_handler(
                    servicer.SetThresholds,
                    request_deserializer=smart__hospital__pb2.SetMonitorThresholdsRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smarthospital.PatientMonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smarthospital.PatientMonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PatientMonitorService(object):
    """services for Monitor
    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.PatientMonitorService/GetState',
            smart__hospital__pb2.DeviceIdRequest.SerializeToString,
            smart__hospital__pb2.PatientMonitorState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.PatientMonitorService/SetPower',
            smart__hospital__pb2.SetMonitorPowerRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAlarmEnabled(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.PatientMonitorService/SetAlarmEnabled',
            smart__hospital__pb2.SetMonitorAlarmRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetThresholds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.PatientMonitorService/SetThresholds',
            smart__hospital__pb2.SetMonitorThresholdsRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HospitalBedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/smarthospital.HospitalBedService/GetState',
                request_serializer=smart__hospital__pb2.DeviceIdRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.HospitalBedState.FromString,
                _registered_method=True)
        self.SetPower = channel.unary_unary(
                '/smarthospital.HospitalBedService/SetPower',
                request_serializer=smart__hospital__pb2.SetBedPowerRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetHeight = channel.unary_unary(
                '/smarthospital.HospitalBedService/SetHeight',
                request_serializer=smart__hospital__pb2.SetHeightRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetWheelsLock = channel.unary_unary(
                '/smarthospital.HospitalBedService/SetWheelsLock',
                request_serializer=smart__hospital__pb2.SetWheelsLockRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetOccupied = channel.unary_unary(
                '/smarthospital.HospitalBedService/SetOccupied',
                request_serializer=smart__hospital__pb2.SetOccupiedRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetEmergencyMode = channel.unary_unary(
                '/smarthospital.HospitalBedService/SetEmergencyMode',
                request_serializer=smart__hospital__pb2.SetEmergencyModeRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)


class HospitalBedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetHeight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetWheelsLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOccupied(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEmergencyMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HospitalBedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=smart__hospital__pb2.DeviceIdRequest.FromString,
                    response_serializer=smart__hospital__pb2.HospitalBedState.SerializeToString,
            ),
            'SetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPower,
                    request_deserializer=smart__hospital__pb2.SetBedPowerRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetHeight': grpc.unary_unary_rpc_method_handler(
                    servicer.SetHeight,
                    request_deserializer=smart__hospital__pb2.SetHeightRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetWheelsLock': grpc.unary_unary_rpc_method_handler(
                    servicer.SetWheelsLock,
                    request_deserializer=smart__hospital__pb2.SetWheelsLockRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetOccupied': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOccupied,
                    request_deserializer=smart__hospital__pb2.SetOccupiedRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetEmergencyMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEmergencyMode,
                    request_deserializer=smart__hospital__pb2.SetEmergencyModeRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smarthospital.HospitalBedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smarthospital.HospitalBedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HospitalBedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalBedService/GetState',
            smart__hospital__pb2.DeviceIdRequest.SerializeToString,
            smart__hospital__pb2.HospitalBedState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalBedService/SetPower',
            smart__hospital__pb2.SetBedPowerRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetHeight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalBedService/SetHeight',
            smart__hospital__pb2.SetHeightRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetWheelsLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalBedService/SetWheelsLock',
            smart__hospital__pb2.SetWheelsLockRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOccupied(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalBedService/SetOccupied',
            smart__hospital__pb2.SetOccupiedRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetEmergencyMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalBedService/SetEmergencyMode',
            smart__hospital__pb2.SetEmergencyModeRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HospitalCameraServiceStub(object):
    """Services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/smarthospital.HospitalCameraService/GetState',
                request_serializer=smart__hospital__pb2.DeviceIdRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.HospitalCameraState.FromString,
                _registered_method=True)
        self.SetPower = channel.unary_unary(
                '/smarthospital.HospitalCameraService/SetPower',
                request_serializer=smart__hospital__pb2.SetCameraPowerRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.SetRecording = channel.unary_unary(
                '/smarthospital.HospitalCameraService/SetRecording',
                request_serializer=smart__hospital__pb2.SetRecordingRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.MoveCamera = channel.unary_unary(
                '/smarthospital.HospitalCameraService/MoveCamera',
                request_serializer=smart__hospital__pb2.MoveCameraRequest.SerializeToString,
                response_deserializer=smart__hospital__pb2.OperationStatus.FromString,
                _registered_method=True)


class HospitalCameraServiceServicer(object):
    """Services
    """

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HospitalCameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=smart__hospital__pb2.DeviceIdRequest.FromString,
                    response_serializer=smart__hospital__pb2.HospitalCameraState.SerializeToString,
            ),
            'SetPower': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPower,
                    request_deserializer=smart__hospital__pb2.SetCameraPowerRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'SetRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRecording,
                    request_deserializer=smart__hospital__pb2.SetRecordingRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
            'MoveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveCamera,
                    request_deserializer=smart__hospital__pb2.MoveCameraRequest.FromString,
                    response_serializer=smart__hospital__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smarthospital.HospitalCameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smarthospital.HospitalCameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HospitalCameraService(object):
    """Services
    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalCameraService/GetState',
            smart__hospital__pb2.DeviceIdRequest.SerializeToString,
            smart__hospital__pb2.HospitalCameraState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalCameraService/SetPower',
            smart__hospital__pb2.SetCameraPowerRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalCameraService/SetRecording',
            smart__hospital__pb2.SetRecordingRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smarthospital.HospitalCameraService/MoveCamera',
            smart__hospital__pb2.MoveCameraRequest.SerializeToString,
            smart__hospital__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
